### ISSUE TITLE
Is there literature comparing performance of your JSONParse  vs the native apex class System.JsonParser ?

### ISSUE THREAD

**Issue by peternoges** [open-force/jsonparse#6]
Very cool library.  Is there literature comparing performance of [your JSONParse](https://github.com/open-force/jsonparse)  vs the [native apex System.JsonParser](https://developer.salesforce.com/docs/atlas.en-us.232.0.apexref.meta/apexref/apex_class_System_JsonParser.htm) ?

**Comment by grekker** [comment]
Short answer, I'm not aware of any comparisons like that that have been done.

Longer answer: This library isn't a deserializer like System.JsonParser. In fact it uses a native sibling to System.JSONParser under the hood (JSON.deserializeUntyped()) to do the deserialization. The library is really about having pleasant accessors for an already-deserialized JSON representation.

A comparison between the native JSON.deserializeUntyped() vs System.JSONParser would be a better approximation.

If you wanted to grab a single element from a string JSON block and no other elements, JSONParser is probably faster. The more you want to access the shape in different ways, the more a library like this starts to pull ahead in performance. This is all speculative, though.
